# Dependencies
markdown:            kramdown
highlighter:         true
gems:                [jekyll-paginate, jekyll-seo-tag]

# Permalinks
permalink:           none

# Setup
title:               code.Oliver
tagline:             'Notes, TBH'
url:                 http://soliveras.com
paginate:            1
baseurl:             /
author:
  name:              Oliver Sumo
  url:               https://soliveras.com
  email:             solivera2g3@gmail.com
  twitter:           solivera2g3

# Custom vars
github:
  repo:              https://github.com/dsolivera/dsolivera.github.io.git

personal_links:
  twitter:           https://twitter.com/solivera2g3

